### PR TITLE
Example detect_variant toil YAML

### PR DESCRIPTION
**Pull request by jasonwalker80**
An example input yaml for detect variants and toil for local testing.

### CODE REVIEW

**Comment by jasonwalker80** [comment]
@tmooney is this useful for setting up the full Exome toil test?

**Comment by tmooney** [comment]
It doesn't hurt anything.  I've been using my own version of the inputs, but if it's handy then +1!

**Comment by jasonwalker80** [comment]
This is out of date. An example file for local execution would still be handy, but this won't be merged as-is.

**Comment by jasonwalker80** [comment]
@tmooney if you have a full exome yaml it might be worthwhile to share as an example_data file. I'm closing this as the existing PR is out of date.

**Pull request closed without merging**
